/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PendienteRouteImport } from './routes/pendiente'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTrabajosRouteImport } from './routes/_authenticated/trabajos'
import { Route as AuthenticatedRecetasRouteImport } from './routes/_authenticated/recetas'
import { Route as AuthenticatedProcesosRouteImport } from './routes/_authenticated/procesos'
import { Route as AuthenticatedPosicionComercialRouteImport } from './routes/_authenticated/posicion-comercial'
import { Route as AuthenticatedPendientesRouteImport } from './routes/_authenticated/pendientes'
import { Route as AuthenticatedOperativaRouteImport } from './routes/_authenticated/operativa'
import { Route as AuthenticatedMensajesRouteImport } from './routes/_authenticated/mensajes'
import { Route as AuthenticatedLaboratorioRouteImport } from './routes/_authenticated/laboratorio'
import { Route as AuthenticatedInformesRouteImport } from './routes/_authenticated/informes'
import { Route as AuthenticatedContratosRouteImport } from './routes/_authenticated/contratos'
import { Route as AuthenticatedComparativaRouteImport } from './routes/_authenticated/comparativa'
import { Route as AuthenticatedCalendarioRouteImport } from './routes/_authenticated/calendario'
import { Route as AuthenticatedBodegaRouteImport } from './routes/_authenticated/bodega'
import { Route as AuthenticatedAlmacenRouteImport } from './routes/_authenticated/almacen'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedActividadRouteImport } from './routes/_authenticated/actividad'

const PendienteRoute = PendienteRouteImport.update({
  id: '/pendiente',
  path: '/pendiente',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTrabajosRoute = AuthenticatedTrabajosRouteImport.update({
  id: '/trabajos',
  path: '/trabajos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRecetasRoute = AuthenticatedRecetasRouteImport.update({
  id: '/recetas',
  path: '/recetas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProcesosRoute = AuthenticatedProcesosRouteImport.update({
  id: '/procesos',
  path: '/procesos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPosicionComercialRoute =
  AuthenticatedPosicionComercialRouteImport.update({
    id: '/posicion-comercial',
    path: '/posicion-comercial',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPendientesRoute = AuthenticatedPendientesRouteImport.update({
  id: '/pendientes',
  path: '/pendientes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOperativaRoute = AuthenticatedOperativaRouteImport.update({
  id: '/operativa',
  path: '/operativa',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMensajesRoute = AuthenticatedMensajesRouteImport.update({
  id: '/mensajes',
  path: '/mensajes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLaboratorioRoute =
  AuthenticatedLaboratorioRouteImport.update({
    id: '/laboratorio',
    path: '/laboratorio',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInformesRoute = AuthenticatedInformesRouteImport.update({
  id: '/informes',
  path: '/informes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContratosRoute = AuthenticatedContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedComparativaRoute =
  AuthenticatedComparativaRouteImport.update({
    id: '/comparativa',
    path: '/comparativa',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCalendarioRoute = AuthenticatedCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBodegaRoute = AuthenticatedBodegaRouteImport.update({
  id: '/bodega',
  path: '/bodega',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAlmacenRoute = AuthenticatedAlmacenRouteImport.update({
  id: '/almacen',
  path: '/almacen',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedActividadRoute = AuthenticatedActividadRouteImport.update({
  id: '/actividad',
  path: '/actividad',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/pendiente': typeof PendienteRoute
  '/actividad': typeof AuthenticatedActividadRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/almacen': typeof AuthenticatedAlmacenRoute
  '/bodega': typeof AuthenticatedBodegaRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/comparativa': typeof AuthenticatedComparativaRoute
  '/contratos': typeof AuthenticatedContratosRoute
  '/informes': typeof AuthenticatedInformesRoute
  '/laboratorio': typeof AuthenticatedLaboratorioRoute
  '/mensajes': typeof AuthenticatedMensajesRoute
  '/operativa': typeof AuthenticatedOperativaRoute
  '/pendientes': typeof AuthenticatedPendientesRoute
  '/posicion-comercial': typeof AuthenticatedPosicionComercialRoute
  '/procesos': typeof AuthenticatedProcesosRoute
  '/recetas': typeof AuthenticatedRecetasRoute
  '/trabajos': typeof AuthenticatedTrabajosRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/pendiente': typeof PendienteRoute
  '/actividad': typeof AuthenticatedActividadRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/almacen': typeof AuthenticatedAlmacenRoute
  '/bodega': typeof AuthenticatedBodegaRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/comparativa': typeof AuthenticatedComparativaRoute
  '/contratos': typeof AuthenticatedContratosRoute
  '/informes': typeof AuthenticatedInformesRoute
  '/laboratorio': typeof AuthenticatedLaboratorioRoute
  '/mensajes': typeof AuthenticatedMensajesRoute
  '/operativa': typeof AuthenticatedOperativaRoute
  '/pendientes': typeof AuthenticatedPendientesRoute
  '/posicion-comercial': typeof AuthenticatedPosicionComercialRoute
  '/procesos': typeof AuthenticatedProcesosRoute
  '/recetas': typeof AuthenticatedRecetasRoute
  '/trabajos': typeof AuthenticatedTrabajosRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/pendiente': typeof PendienteRoute
  '/_authenticated/actividad': typeof AuthenticatedActividadRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/almacen': typeof AuthenticatedAlmacenRoute
  '/_authenticated/bodega': typeof AuthenticatedBodegaRoute
  '/_authenticated/calendario': typeof AuthenticatedCalendarioRoute
  '/_authenticated/comparativa': typeof AuthenticatedComparativaRoute
  '/_authenticated/contratos': typeof AuthenticatedContratosRoute
  '/_authenticated/informes': typeof AuthenticatedInformesRoute
  '/_authenticated/laboratorio': typeof AuthenticatedLaboratorioRoute
  '/_authenticated/mensajes': typeof AuthenticatedMensajesRoute
  '/_authenticated/operativa': typeof AuthenticatedOperativaRoute
  '/_authenticated/pendientes': typeof AuthenticatedPendientesRoute
  '/_authenticated/posicion-comercial': typeof AuthenticatedPosicionComercialRoute
  '/_authenticated/procesos': typeof AuthenticatedProcesosRoute
  '/_authenticated/recetas': typeof AuthenticatedRecetasRoute
  '/_authenticated/trabajos': typeof AuthenticatedTrabajosRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pendiente'
    | '/actividad'
    | '/admin'
    | '/almacen'
    | '/bodega'
    | '/calendario'
    | '/comparativa'
    | '/contratos'
    | '/informes'
    | '/laboratorio'
    | '/mensajes'
    | '/operativa'
    | '/pendientes'
    | '/posicion-comercial'
    | '/procesos'
    | '/recetas'
    | '/trabajos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/pendiente'
    | '/actividad'
    | '/admin'
    | '/almacen'
    | '/bodega'
    | '/calendario'
    | '/comparativa'
    | '/contratos'
    | '/informes'
    | '/laboratorio'
    | '/mensajes'
    | '/operativa'
    | '/pendientes'
    | '/posicion-comercial'
    | '/procesos'
    | '/recetas'
    | '/trabajos'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/pendiente'
    | '/_authenticated/actividad'
    | '/_authenticated/admin'
    | '/_authenticated/almacen'
    | '/_authenticated/bodega'
    | '/_authenticated/calendario'
    | '/_authenticated/comparativa'
    | '/_authenticated/contratos'
    | '/_authenticated/informes'
    | '/_authenticated/laboratorio'
    | '/_authenticated/mensajes'
    | '/_authenticated/operativa'
    | '/_authenticated/pendientes'
    | '/_authenticated/posicion-comercial'
    | '/_authenticated/procesos'
    | '/_authenticated/recetas'
    | '/_authenticated/trabajos'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PendienteRoute: typeof PendienteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pendiente': {
      id: '/pendiente'
      path: '/pendiente'
      fullPath: '/pendiente'
      preLoaderRoute: typeof PendienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trabajos': {
      id: '/_authenticated/trabajos'
      path: '/trabajos'
      fullPath: '/trabajos'
      preLoaderRoute: typeof AuthenticatedTrabajosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recetas': {
      id: '/_authenticated/recetas'
      path: '/recetas'
      fullPath: '/recetas'
      preLoaderRoute: typeof AuthenticatedRecetasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/procesos': {
      id: '/_authenticated/procesos'
      path: '/procesos'
      fullPath: '/procesos'
      preLoaderRoute: typeof AuthenticatedProcesosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/posicion-comercial': {
      id: '/_authenticated/posicion-comercial'
      path: '/posicion-comercial'
      fullPath: '/posicion-comercial'
      preLoaderRoute: typeof AuthenticatedPosicionComercialRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pendientes': {
      id: '/_authenticated/pendientes'
      path: '/pendientes'
      fullPath: '/pendientes'
      preLoaderRoute: typeof AuthenticatedPendientesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/operativa': {
      id: '/_authenticated/operativa'
      path: '/operativa'
      fullPath: '/operativa'
      preLoaderRoute: typeof AuthenticatedOperativaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mensajes': {
      id: '/_authenticated/mensajes'
      path: '/mensajes'
      fullPath: '/mensajes'
      preLoaderRoute: typeof AuthenticatedMensajesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/laboratorio': {
      id: '/_authenticated/laboratorio'
      path: '/laboratorio'
      fullPath: '/laboratorio'
      preLoaderRoute: typeof AuthenticatedLaboratorioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/informes': {
      id: '/_authenticated/informes'
      path: '/informes'
      fullPath: '/informes'
      preLoaderRoute: typeof AuthenticatedInformesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contratos': {
      id: '/_authenticated/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof AuthenticatedContratosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/comparativa': {
      id: '/_authenticated/comparativa'
      path: '/comparativa'
      fullPath: '/comparativa'
      preLoaderRoute: typeof AuthenticatedComparativaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendario': {
      id: '/_authenticated/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedCalendarioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bodega': {
      id: '/_authenticated/bodega'
      path: '/bodega'
      fullPath: '/bodega'
      preLoaderRoute: typeof AuthenticatedBodegaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/almacen': {
      id: '/_authenticated/almacen'
      path: '/almacen'
      fullPath: '/almacen'
      preLoaderRoute: typeof AuthenticatedAlmacenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/actividad': {
      id: '/_authenticated/actividad'
      path: '/actividad'
      fullPath: '/actividad'
      preLoaderRoute: typeof AuthenticatedActividadRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedActividadRoute: typeof AuthenticatedActividadRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAlmacenRoute: typeof AuthenticatedAlmacenRoute
  AuthenticatedBodegaRoute: typeof AuthenticatedBodegaRoute
  AuthenticatedCalendarioRoute: typeof AuthenticatedCalendarioRoute
  AuthenticatedComparativaRoute: typeof AuthenticatedComparativaRoute
  AuthenticatedContratosRoute: typeof AuthenticatedContratosRoute
  AuthenticatedInformesRoute: typeof AuthenticatedInformesRoute
  AuthenticatedLaboratorioRoute: typeof AuthenticatedLaboratorioRoute
  AuthenticatedMensajesRoute: typeof AuthenticatedMensajesRoute
  AuthenticatedOperativaRoute: typeof AuthenticatedOperativaRoute
  AuthenticatedPendientesRoute: typeof AuthenticatedPendientesRoute
  AuthenticatedPosicionComercialRoute: typeof AuthenticatedPosicionComercialRoute
  AuthenticatedProcesosRoute: typeof AuthenticatedProcesosRoute
  AuthenticatedRecetasRoute: typeof AuthenticatedRecetasRoute
  AuthenticatedTrabajosRoute: typeof AuthenticatedTrabajosRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedActividadRoute: AuthenticatedActividadRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAlmacenRoute: AuthenticatedAlmacenRoute,
  AuthenticatedBodegaRoute: AuthenticatedBodegaRoute,
  AuthenticatedCalendarioRoute: AuthenticatedCalendarioRoute,
  AuthenticatedComparativaRoute: AuthenticatedComparativaRoute,
  AuthenticatedContratosRoute: AuthenticatedContratosRoute,
  AuthenticatedInformesRoute: AuthenticatedInformesRoute,
  AuthenticatedLaboratorioRoute: AuthenticatedLaboratorioRoute,
  AuthenticatedMensajesRoute: AuthenticatedMensajesRoute,
  AuthenticatedOperativaRoute: AuthenticatedOperativaRoute,
  AuthenticatedPendientesRoute: AuthenticatedPendientesRoute,
  AuthenticatedPosicionComercialRoute: AuthenticatedPosicionComercialRoute,
  AuthenticatedProcesosRoute: AuthenticatedProcesosRoute,
  AuthenticatedRecetasRoute: AuthenticatedRecetasRoute,
  AuthenticatedTrabajosRoute: AuthenticatedTrabajosRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PendienteRoute: PendienteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
