/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTrabajosRouteImport } from './routes/_authenticated/trabajos'
import { Route as AuthenticatedRecetasRouteImport } from './routes/_authenticated/recetas'
import { Route as AuthenticatedPendientesRouteImport } from './routes/_authenticated/pendientes'
import { Route as AuthenticatedMensajesRouteImport } from './routes/_authenticated/mensajes'
import { Route as AuthenticatedBodegaRouteImport } from './routes/_authenticated/bodega'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedActividadRouteImport } from './routes/_authenticated/actividad'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTrabajosRoute = AuthenticatedTrabajosRouteImport.update({
  id: '/trabajos',
  path: '/trabajos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRecetasRoute = AuthenticatedRecetasRouteImport.update({
  id: '/recetas',
  path: '/recetas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPendientesRoute = AuthenticatedPendientesRouteImport.update({
  id: '/pendientes',
  path: '/pendientes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMensajesRoute = AuthenticatedMensajesRouteImport.update({
  id: '/mensajes',
  path: '/mensajes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBodegaRoute = AuthenticatedBodegaRouteImport.update({
  id: '/bodega',
  path: '/bodega',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedActividadRoute = AuthenticatedActividadRouteImport.update({
  id: '/actividad',
  path: '/actividad',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/actividad': typeof AuthenticatedActividadRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/bodega': typeof AuthenticatedBodegaRoute
  '/mensajes': typeof AuthenticatedMensajesRoute
  '/pendientes': typeof AuthenticatedPendientesRoute
  '/recetas': typeof AuthenticatedRecetasRoute
  '/trabajos': typeof AuthenticatedTrabajosRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/actividad': typeof AuthenticatedActividadRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/bodega': typeof AuthenticatedBodegaRoute
  '/mensajes': typeof AuthenticatedMensajesRoute
  '/pendientes': typeof AuthenticatedPendientesRoute
  '/recetas': typeof AuthenticatedRecetasRoute
  '/trabajos': typeof AuthenticatedTrabajosRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/actividad': typeof AuthenticatedActividadRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/bodega': typeof AuthenticatedBodegaRoute
  '/_authenticated/mensajes': typeof AuthenticatedMensajesRoute
  '/_authenticated/pendientes': typeof AuthenticatedPendientesRoute
  '/_authenticated/recetas': typeof AuthenticatedRecetasRoute
  '/_authenticated/trabajos': typeof AuthenticatedTrabajosRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/actividad'
    | '/admin'
    | '/bodega'
    | '/mensajes'
    | '/pendientes'
    | '/recetas'
    | '/trabajos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/actividad'
    | '/admin'
    | '/bodega'
    | '/mensajes'
    | '/pendientes'
    | '/recetas'
    | '/trabajos'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/actividad'
    | '/_authenticated/admin'
    | '/_authenticated/bodega'
    | '/_authenticated/mensajes'
    | '/_authenticated/pendientes'
    | '/_authenticated/recetas'
    | '/_authenticated/trabajos'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trabajos': {
      id: '/_authenticated/trabajos'
      path: '/trabajos'
      fullPath: '/trabajos'
      preLoaderRoute: typeof AuthenticatedTrabajosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recetas': {
      id: '/_authenticated/recetas'
      path: '/recetas'
      fullPath: '/recetas'
      preLoaderRoute: typeof AuthenticatedRecetasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pendientes': {
      id: '/_authenticated/pendientes'
      path: '/pendientes'
      fullPath: '/pendientes'
      preLoaderRoute: typeof AuthenticatedPendientesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mensajes': {
      id: '/_authenticated/mensajes'
      path: '/mensajes'
      fullPath: '/mensajes'
      preLoaderRoute: typeof AuthenticatedMensajesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bodega': {
      id: '/_authenticated/bodega'
      path: '/bodega'
      fullPath: '/bodega'
      preLoaderRoute: typeof AuthenticatedBodegaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/actividad': {
      id: '/_authenticated/actividad'
      path: '/actividad'
      fullPath: '/actividad'
      preLoaderRoute: typeof AuthenticatedActividadRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedActividadRoute: typeof AuthenticatedActividadRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBodegaRoute: typeof AuthenticatedBodegaRoute
  AuthenticatedMensajesRoute: typeof AuthenticatedMensajesRoute
  AuthenticatedPendientesRoute: typeof AuthenticatedPendientesRoute
  AuthenticatedRecetasRoute: typeof AuthenticatedRecetasRoute
  AuthenticatedTrabajosRoute: typeof AuthenticatedTrabajosRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedActividadRoute: AuthenticatedActividadRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBodegaRoute: AuthenticatedBodegaRoute,
  AuthenticatedMensajesRoute: AuthenticatedMensajesRoute,
  AuthenticatedPendientesRoute: AuthenticatedPendientesRoute,
  AuthenticatedRecetasRoute: AuthenticatedRecetasRoute,
  AuthenticatedTrabajosRoute: AuthenticatedTrabajosRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
